- name: Setup Docker on ubuntu
  hosts: EC2_Server
  become: yes
  tasks:
    - name: Install curl package
      apt:
        name: curl
        state: present

    - name: Add Docker GPG key to trusted keys 
      shell: sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
             | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
    
    - name: Add Docker repository using add-apt-repository module
      apt_repository: 
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt package cache again after adding Docker repository
      apt:
        update_cache: yes

    - name: Install required packages for Docker installation
      apt:
        name:
          - lsb-release
          - gnupg
          - apt-transport-https
          - ca-certificates 
        state : present 

    - name : Install Docker 
      apt :
        name :
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
        state : present 

    - name : Add the current user to the docker group 
      user :
        name : ubuntu
        groups : docker 
        append : yes 

    - name: Start and enable Docker service
      service:
        name: docker
        enabled: yes
        state: started

          
