- name: Setup Jenkins
  hosts: EC2_Server
  become: yes

  tasks: 

    - name: Download Jenkins keyring
      become_user: ubuntu
      command: sudo wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key

    - name: Add Jenkins repository to sources list
      become_user: ubuntu
      shell: echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
               https://pkg.jenkins.io/debian-stable binary/ |sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Install fontconfig and openjdk-17-jre
      apt:
        name:
          - fontconfig
          - openjdk-17-jre
        update_cache: yes
        state: present

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Jenkins package  
      apt:
        name: jenkins
        state: latest

    - name: Start jenkins Service  
      service:
        name: jenkins
        enabled: yes  
        state: started    
